services:
    app:
        image: livearchive-laravel
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
          AWS_ACCESS_KEY_ID: livearchive
          AWS_SECRET_ACCESS_KEY: password
          AWS_DEFAULT_REGION: us-east-1
          AWS_BUCKET: livearchive
          AWS_USE_PATH_STYLE_ENDPOINT: true
          AWS_URL: http://localhost:9000/local
          AWS_ENDPOINT: http://minio:9000
          DB_HOST: mysql
          LIVEARCHIVE_LAYOUT: gmail
          LIVEARCHIVE_DB_HOST: ""
          LIVEARCHIVE_DB_DATABASE: ""
          LIVEARCHIVE_DB_USERNAME: livearchive
          LIVEARCHIVE_DB_PASSWORD: password
        networks:
            - livearchive
        depends_on:
            - mysql
            - minio
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'livearchive'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            LIVEARCHIVE_DB_DATABASE: livearchive
            LIVEARCHIVE_DB_USERNAME: livearchive
            LIVEARCHIVE_DB_PASSWORD: password
        volumes:
            - 'livearchive-mysql:/var/lib/mysql'
            - './docker/mysql/create-livearchive-database.sh:/docker-entrypoint-initdb.d/10-create-livearchive-database.sh'
        networks:
            - livearchive
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    minio:
        image: 'minio/minio:latest'
        environment:
            MINIO_ROOT_USER: livearchive
            MINIO_ROOT_PASSWORD: password
        volumes:
            - 'livearchive-minio:/data/minio'
        networks:
            - livearchive
        command: 'minio server /data/minio --console-address ":9001"'
        ports:
          - '${FORWARD_MINIO_PORT:-9000}:9000'
          - '${FORWARD_MINIO_CONSOLE_PORT:-9001}:9001'
networks:
    livearchive:
        driver: bridge
volumes:
    livearchive-mysql:
        driver: local
    livearchive-minio:
        driver: local
