/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        "./resources/views/*.blade.php",
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "node_modules/preline/dist/*.js",
    ],
    theme: {
        extend: {
            colors: {
               "dark": {
                    "background": "#1d1d1d",
                    "background-800": "#3a3939",
                    "background-700": "#565656",
                    "background-400": "#a6a5a5",
                    "background-500": "#908f8f",
                    "background-100": "#e9e9e9",
                    "header-font":"#ffffff",
                    "font": "#ffffff",
                    "font-msg": "#a6a5a5",
                   "font-office": "#565656",
                    "font-header-msg": "#565656",
                   "font-description": "#737272",
                   "font-list": "#a6a5a5",
                   "font-link":"#6879ce",
                    "list-message": "#d3d2d2",
                    "hover-list-gmail": "#385ac4",
                    "hover-list-office": "#385ac4",
                    "bg-inside-msg": "#ffffff",
                    "btn-blue":"#1d4ed8",
                    "light":"#3a3939",
                    "neutral":"#565656",
                    "hover-btn-blue":"#021368",
                    "icons": "#e9e9e9",
                    "hover-icons": "#908f8f",
                    "icons-attachment": "#38baf5",
                    "description": "#bcbcbc",
                    "border": "#565656",
                    "text-sky": "#38baf5",
                    "description-office": "#908f8f",
                   "icon-form": "#e9e9e9",
                   "font-icon-form":"#565656",
                   "error": "#a43c3c",
                   "selected": "#1e1b4b"

                },

                "light": {
                    "background": "#ffffff",
                    "background-100": "#3a3939",
                    "background-200": "#565656",
                    "background-400": "#908f8f",
                    "background-600": "#a6a5a5",
                    "background-800": "#e9e9e9",
                    "background-header": "#0631b5",
                    "header-font":"#ffffff",
                    "font": "#000000",
                    "font-header-msg": "#a6a5a5",
                    "font-initial-msg": "#737272",
                    "font-header-icons-msg": "#737272",
                    "font-msg": "#565656",
                    "font-link":"#6879ce",
                    "font-description": "#737272",
                    "icons": "#ffffff",
                    "hover-icons": "#9bade1",
                    "hover-msg": "#E6EAF8",
                    "subject-list": "#0631b5",
                    "btn-blue":"#1d4ed8",
                    "light":"#ffffff",
                    "neutral":"#565656",
                    "hover-btn-blue":"#031fad",
                    "icon-form": "#e6e9f7",
                    "font-icon-form":"#031fad",
                    "error": "#e84d4d",
                    "selected": "#eef2ff"

                },
                // "light": {
                //     "background": "#ffffff",
                //     "background-header": "#ffffff",
                //     "header-font":"#ffffff",
                //      "font": "#000000",
                //      "font-header-msg": "#a6a5a5",
                //      "font-initial-msg": "#737272",
                //      "font-header-icons-msg": "#737272",
                //      "font-msg": "#565656",
               //      "icons": "#737272",
                //     "hover-icons": "#565656",
                //      "hover-msg": "#e9e9e9",
                //      "subject-list": "#0631b5",
                //      "btn-blue":"#02198a",
                //       "hover-btn-blue":"#021368",
                // },
                // "dark": {
                //     "background": "#021448",
                //     "background-800": "#041D6D",
                //     "background-700": "#565656",
                //     "background-400": "#a6a5a5",
                //     "background-500": "#908f8f",
                //     "background-100": "#e9e9e9",
                //     "header-font":"#ffffff",
                //     "font": "#ffffff",
                //     "font-msg": "#3a3939",
                //     "list-message": "#d3d2d2",
                //     "hover-list-gmail": "#385ac4",
                //     "hover-list-office": "#385ac4",
                //     "bg-inside-msg": "#ffffff",
                //     "btn-blue":"#02198a",
                //     "hover-btn-blue":"#021368",
                //     "icons": "#e9e9e9",
                //     "hover-icons": "#908f8f",
                //     "icons-attachment": "#38baf5",
                //     "description": "#bcbcbc",
                //     "font-list": "#a6a5a5",
                //     "border": "#565656",
                //     "font-office": "#565656",
                //     "text-sky": "#38baf5",
                //     "description-office": "#908f8f",
                //
                //
                // },



            },
            screens: {
                print: { raw: 'print' },
                screen: { raw: 'screen' },
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('preline/plugin'),
    ],
}
