#!/usr/bin/env bash

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS $LIVEARCHIVE_DB_DATABASE;
    GRANT ALL PRIVILEGES ON \`$LIVEARCHIVE_DB_DATABASE%\`.* TO '$LIVEARCHIVE_DB_USERNAME'@'%';
EOSQL
